### ISSUE TITLE
422 Error via Mapathon Summary Queries

### ISSUE THREAD

**Issue by d-rita** [hotosm/galaxy-ui#18]
This error occurred when this payload: `{
  “fromTimestamp”:“2021-09-23T18:30:00.000Z”,
  “toTimestamp”:“2021-09-24T18:15:00.000Z”,
  “projectIds”:[],
  “hashtags”:[“mapandchathour2021”]
}` was sent to the backend server. The error returned is `422 Unprocessable Entity`.  The source of the error is the '_Z_' character at the end of the dates.

**Comment by itskshitiz321** [comment]
yes, you are right !
