### ISSUE TITLE
Change Wireframe to Highway count instead of Km 

### ISSUE THREAD

**Issue by itskshitiz321** [hotosm/galaxy-ui#28]
![image](https://user-images.githubusercontent.com/36752999/147670185-4acb81ca-962b-4352-95e3-a26d0e32de72.png)
I believe the stats we are returning is count of highway feature , Is it in Km ? Need confirmation cc : @omranlm

**Comment by omranlm** [comment]
Yes, confirming that the returned value is the total number of highways added and modified in the results query 

@d-rita the added highways total number can be found in the "mappedFeatures" returned results in the API but getting 
"feature" == "highway" and "action": "create" for specific "username"

The results are not accurate in the UI grid @ramyaragupathy 

![image](https://user-images.githubusercontent.com/39491329/148757723-ba6668bd-3f7b-4c95-832b-32073477d4da.png)

**Comment by ramyaragupathy** [comment]
@omranlm - by accuracy do you mean just the highway count or do you notice other mismatching numbers in the grid?

cc @d-rita @itskshitiz321

**Comment by omranlm** [comment]
@ramyaragupathy the total number of "buildings added" for  for that specific username is 119 as it appears in the API results while it shows 123 in the UI grid, that user has 4 building modified 
and confirming the highways returned results is the count of added and modified highways so grid header is not accurate

**Comment by d-rita** [comment]
Traced the error to the utils function being used to sort the mapathon data. https://github.com/hotosm/galaxy-ui/blob/40864e065001586bf30cac2cc3b14d9dc8c9243a/src/utils/sortMapathonResultsData.js#L12. Keyword is supposed to be "create" not "modify". I'll fix that @omranlm

**Comment by omranlm** [comment]
@d-rita the 

- Buildings added count is also not accurate and it should come from mappedFeatures with "building", "create" keywords
- Header for highway - remove the (KM)

**Comment by d-rita** [comment]
- Headers (km) have been removed as of this [PR](https://github.com/hotosm/galaxy-ui/pull/31). 
- For buildings count, I was using the `totalBuildings` count in the `contributors`' section of the response. But I can change that to be calculated as well.
