### ISSUE TITLE
Set up linting for the project

### ISSUE THREAD

**Issue by d-rita** [hotosm/galaxy-ui#38]
Enforce linting for all files added to the project. This ensures that all code committed is formatted in a uniform manner. For this setup, the following [guidelines](https://create-react-app.dev/docs/setting-up-your-editor/#formatting-code-automatically) in the CRA documentation will be used.

**Comment by itskshitiz321** [comment]
This is an interesting issue , which can be implemented in our other products as well , would be good enhancement
cc: @ramyaragupathy
