### ISSUE TITLE
Galaxy UI is not communicating to Insight Database Properly 

### ISSUE THREAD

**Issue by itskshitiz321** [hotosm/galaxy-ui#40]
During testing of user group report , when we pass multiple users at a time , Query didn't reached to database . From API It is working well. From Galaxy UI we are having trouble , Using local setup of UI and API is working fine

**Comment by itskshitiz321** [comment]
cc: @dakotabenjamin @d-rita @ramyaragupathy

**Comment by itskshitiz321** [comment]
![image](https://user-images.githubusercontent.com/36752999/152978636-0dbc9386-c1e7-4e45-a833-9065389ed42f.png)
Its been more than hour since I ran this request from production site

**Comment by ramyaragupathy** [comment]
@d-rita @itskshitiz321 - is this still an issue?

**Comment by itskshitiz321** [comment]
No its solved already @ramyaragupathy
