### ISSUE TITLE
Scheduling and conducting user interviews

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/galaxy-ui#66]
Using this ticket to track progress on user interview for the UX research. cc @chrxiao

**Comment by ramyaragupathy** [comment]
cc @chrxiao

**Comment by chrxiao** [comment]
All but 1 (Jacob) completed. Recordings here: https://drive.google.com/drive/folders/19_Hhi2m6HgibG0gE3EyTrsrrCNV5-ECi?usp=sharing

**Comment by chrxiao** [comment]
All completed!
