### ISSUE TITLE
Ideation for website wireframes

### ISSUE THREAD

**Issue by chrxiao** [hotosm/galaxy-ui#72]
Generate broad ideas and initial sketches for the design of the platform

**Comment by chrxiao** [comment]
In initial stages for each feature: 

General framing of customizable views:
![gen custom frame](https://user-images.githubusercontent.com/40709446/160256985-02cc7c5e-7927-4719-b6d3-52f0f1730bff.png)

Team data analytics widgets:
[Managers pages subfeature.pdf](https://github.com/hotosm/galaxy-ui/files/8356344/Note.Mar.18.2022.pdf)
[User saving playlist subfeature.pdf](https://github.com/hotosm/galaxy-ui/files/8356345/Note.Mar.22.2022.pdf)

**Comment by ramyaragupathy** [comment]
This is complete
